In [129]:
import pandas as pd
import numpy as np
import matplotlib
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics import confusion_matrix,f1_score

In [130]:
train = pd.read_csv("train_ready_for_model_ins.csv")
train.head()

principal component 1  principal component 2  principal component 3  \
0               4.156702              -0.939636              -0.891017   
1              -1.708711              -0.376629               0.026695   
2               8.911210              -0.862539              -0.618071   
3               2.137490              -3.416324               0.803450   
4              -1.689057              -0.330288               0.005043   

   principal component 4  principal component 5  principal component 6  \
0              -2.682153              -1.650308               1.289457   
1              -0.237419              -0.730520               0.240316   
2              -3.107301              -3.677199               2.056153   
3               4.072160               0.255350              -0.325482   
4              -0.316986              -0.903165               0.311182   

   principal component 7  principal component 8  principal component 9  \
0              -3.862679              -3.451789               1.566266   
1              -0.674297               0.029415              -0.222598   
2              -1.256020              -3.742548               2.140296   
3               2.745004               0.491631              -0.093186   
4              -0.814406               0.026727              -0.268808   

   principal component 10   ...    principal component 14  \
0                2.626448   ...                  0.371168   
1               -1.104547   ...                  0.056212   
2                4.253356   ...                  0.144640   
3                0.356134   ...                  0.133624   
4               -1.262762   ...                  0.055768   

   principal component 15  principal component 16  principal component 17  \
0               -0.491994               -1.543746               -0.149809   
1                0.054695               -0.330661               -0.141436   
2                0.370062               -0.143246               -0.281820   
3               -1.936436                1.002474               -1.408193   
4                0.081791               -0.336995               -0.140550   

   principal component 18  principal component 19  principal component 20  \
0                0.334036                1.544898                0.031054   
1                0.018368                0.273320                0.227839   
2               -0.408889               -0.200952                0.023153   
3                0.103298               -1.174440               -1.280386   
4                0.003486                0.300149                0.195273   

       ID      TARGET1  TARGET  
0  142882  2807855.303     1.0  
1  116073        0.000     0.0  
2   40727        0.000     0.0  
3   96753        0.000     0.0  
4  105319        0.000     0.0  

[5 rows x 23 columns]

In [131]:
test = pd.read_csv("test_ready_for_model_ins.csv")
test.head()

principal component 1  principal component 2  principal component 3  \
0               4.243311              -1.351888              -0.501955   
1               1.725746              -0.477560              -0.262628   
2              -1.645877              -0.346278              -0.208765   
3              -1.022190               0.080477              -0.180327   
4              -1.375740              -0.114235              -0.245042   

   principal component 4  principal component 5  principal component 6  \
0              -3.356226              -1.281131               0.525763   
1              -2.359657               1.788699               0.306651   
2              -0.849305               0.381880              -0.047531   
3              -0.757586               0.652738              -0.114229   
4              -1.179933               0.451596              -0.028642   

   principal component 7  principal component 8  principal component 9  \
0              -0.497044              -3.833542              -3.786889   
1               0.063318               1.164027               0.438654   
2              -0.087066              -0.820992              -0.610055   
3              -0.074529              -0.922882              -0.620837   
4              -0.115877              -1.132067              -0.705358   

   principal component 10   ...    principal component 12  \
0                5.946890   ...                  0.259763   
1               -1.984541   ...                 -0.502703   
2               -1.066480   ...                 -0.273242   
3               -0.991713   ...                 -0.214943   
4               -1.411288   ...                 -0.009344   

   principal component 13  principal component 14  principal component 15  \
0                1.414199               -0.592963                0.647460   
1                0.631971               -0.547617                0.041082   
2                0.235557               -0.183462                0.334006   
3               -0.581002                0.236269               -0.354707   
4                0.269595               -0.132203                0.363560   

   principal component 16  principal component 17  principal component 18  \
0                0.068508               -0.108315                1.994468   
1               -0.210688                0.328673                0.810417   
2                0.010562               -0.143212                0.134405   
3               -0.357249                0.230267               -0.137424   
4               -0.023478               -0.128083                0.193353   

   principal component 19  principal component 20      ID  
0                0.894911               -0.677514   64252  
1                0.501021               -0.404309   31278  
2                0.028112                0.098541  148245  
3               -0.191651               -0.212951  133657  
4                0.061192                0.066576   68463  

[5 rows x 21 columns]

In [125]:
train.TARGET.value_counts()

0.0    12715
1.0     1284
Name: TARGET, dtype: int64

In [122]:
test.shape

(5806, 26)

In [132]:
ss = pd.read_csv("Result Evaluation.csv")
#ss.TARGET.value_counts()

In [133]:
ss['TARGET1']=ss.TARGET
ss.loc[ss['TARGET']!=0.000,'TARGET']=1
ss['TARGET']=ss.TARGET.astype('float64')
ss.TARGET.value_counts()

0.0    5282
1.0     524
Name: TARGET, dtype: int64

In [134]:
#Define target and ID columns:
target = 'TARGET'
target1 = 'TARGET1'
IDcol = ['ID']

def modelfit(alg,dtrain,dtest,predictors,target,IDcol,filename):
    from sklearn.metrics import confusion_matrix
    #fit the algorithm on the data
    alg.fit(dtrain[predictors],dtrain[target])
    
    #predict training set
    dtrain_predictions=alg.predict(dtrain[predictors])
    
    #Error Metrics
    #confusion_matrix = confusion_matrix(dtrain[target], dtrain_predictions)
    #print(confusion_matrix)
    
    #Accuracy Train
    #print('Accuracy of classifier on train set: {:.2f}'.format(alg.score(dtrain[predictors],dtrain[target])))
    
    #F1 SCORE
    print('F1 SCORE train',f1_score(dtrain[target],dtrain_predictions,average='weighted'))
    
    #predict test set
    dtest[target]=alg.predict(dtest[predictors])
    
    #F1 SCORE
    print('F1 SCORE test',f1_score(ss.TARGET,dtest[target],average='weighted'))
    
    #Error Metrics
    #confusion_matrix = confusion_matrix(ss.TARGET,dtest[target])
    #print(confusion_matrix)
       
    #Export Submission File:
    IDcol.append(target)

    submission=pd.DataFrame({x:dtest[x] for x in IDcol})
    #submission=pd.DataFrame(dtest['Loan_ID'])
    #submission['Loan_Status']=dtest[target]
    #submission['Loan_Status']=submission.Loan_Status.replace({1:'Y',0:'N'})
    submission.to_csv(filename,index=False)
    #dtest.to_csv(filename,index=False)
    

In [135]:
#1.Logistic Regression
from sklearn.linear_model import LogisticRegression
predictors=[x for x in train.columns if x not in [IDcol,target,target1]]
print('Predictors:',predictors)
alg1=LogisticRegression()
modelfit(alg1,train,test,predictors,target,IDcol,'res2.csv')
#logreg = LogisticRegression()
#logreg.fit(X,Y)

Predictors: ['principal component 1', 'principal component 2', 'principal component 3', 'principal component 4', 'principal component 5', 'principal component 6', 'principal component 7', 'principal component 8', 'principal component 9', 'principal component 10', 'principal component 11', 'principal component 12', 'principal component 13', 'principal component 14', 'principal component 15', 'principal component 16', 'principal component 17', 'principal component 18', 'principal component 19', 'principal component 20', 'ID']
F1 SCORE train 0.8646230107784841
F1 SCORE test 0.8667553692527856


In [136]:
#test.TARGET.value_counts()
res = pd.read_csv("res2.csv")
res.TARGET.value_counts()

0.0    5806
Name: TARGET, dtype: int64

In [ ]:
#Define target and ID columns:
target = 'TARGET'
target1 = 'TARGET1'
IDcol = ['ID']

def modelfit(alg,dtrain,dtest,predictors,target,IDcol,filename):
    from sklearn.metrics import confusion_matrix
    #fit the algorithm on the data
    alg.fit(dtrain[predictors],dtrain[target])
    
    #predict training set
    dtrain_predictions=alg.predict(dtrain[predictors])
    
    #Error Metrics
    confusion_matrix = confusion_matrix(dtrain[target], dtrain_predictions)
    print(confusion_matrix)
    
    #Accuracy Train
    print('Accuracy of classifier on train set: {:.2f}'.format(alg.score(dtrain[predictors],dtrain[target])))
    
    #F1 SCORE
    print('F1 SCORE train',f1_score(dtrain[target],dtrain_predictions,average='weighted'))
    
    #predict test set
    dtest[target]=alg.predict(dtest[predictors])
    
    #F1 SCORE
    print('F1 SCORE test',f1_score(ss.TARGET,dtest[target],average='weighted'))
    
    #Error Metrics
    #confusion_matrix = confusion_matrix(ss.TARGET,dtest[target])
    #print(confusion_matrix)
       
    #Export Submission File:
    IDcol.append(target)

    submission=pd.DataFrame({x:dtest[x] for x in IDcol})
    #submission=pd.DataFrame(dtest['Loan_ID'])
    #submission['Loan_Status']=dtest[target]
    #submission['Loan_Status']=submission.Loan_Status.replace({1:'Y',0:'N'})
    submission.to_csv(filename,index=False)
    #dtest.to_csv(filename,index=False)
    

In [ ]:
from sklearn.linear_model import LinearRegression
predictors = [x for x in train.columns if x not in [target]+IDcol]
print("predictors : ",predictors)
# print predictors
alg1 = LinearRegression(normalize=True)
modelfit(alg1, train, test, predictors, target, IDcol, 'res2.csv')
coef1 = pd.Series(alg1.coef_, predictors).sort_values()
coef1.plot(kind='bar', title='Model Coefficients')

In [173]:
#2.KNN
from sklearn.neighbors import KNeighborsClassifier
#k = 5
predictors=[x for x in train.columns if x not in [target]+IDcol]
print('Predictors:',predictors)
for i in range(1,20):
    alg1=KNeighborsClassifier(n_neighbors = i)
    modelfit(alg1,train,test,predictors,target,IDcol,'res_KNN.csv')

Predictors: ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History', 'Gender_Female', 'Gender_Male', 'Married_No', 'Married_Yes', 'Dependents_0', 'Dependents_1', 'Dependents_2', 'Dependents_3+', 'Education_Graduate', 'Education_Not Graduate', 'Self_Employed_No', 'Self_Employed_Yes', 'Property_Area_Rural', 'Property_Area_Semiurban', 'Property_Area_Urban']
[[192   0]
 [  0 422]]
Accuracy of classifier on train set: 1.00
[[192   0]
 [124 298]]
Accuracy of classifier on train set: 0.80
[[ 99  93]
 [ 43 379]]
Accuracy of classifier on train set: 0.78
[[122  70]
 [ 85 337]]
Accuracy of classifier on train set: 0.75
[[ 64 128]
 [ 38 384]]
Accuracy of classifier on train set: 0.73
[[ 93  99]
 [ 72 350]]
Accuracy of classifier on train set: 0.72
[[ 50 142]
 [ 26 396]]
Accuracy of classifier on train set: 0.73
[[ 63 129]
 [ 56 366]]
Accuracy of classifier on train set: 0.70
[[ 37 155]
 [ 21 401]]
Accuracy of classifier on train set: 0.71
[[ 54 138]
 [ 37 385]]

In [161]:
#3.Decision Tree
from sklearn.tree import DecisionTreeClassifier
#k = 5
predictors=[x for x in train.columns if x not in [target]+IDcol]
print('Predictors:',predictors)
alg1=DecisionTreeClassifier(max_depth=10, min_samples_leaf=60)
modelfit(alg1,train,test,predictors,target,IDcol,'res_DesTree.csv')

Predictors: ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History', 'Gender_Female', 'Gender_Male', 'Married_No', 'Married_Yes', 'Dependents_0', 'Dependents_1', 'Dependents_2', 'Dependents_3+', 'Education_Graduate', 'Education_Not Graduate', 'Self_Employed_No', 'Self_Employed_Yes', 'Property_Area_Rural', 'Property_Area_Semiurban', 'Property_Area_Urban']
[[ 82 110]
 [  7 415]]
Accuracy of classifier on test set: 0.81


In [139]:
grid_param= {'n_estimators': [50, 80,100,200,300],
             'criterion' : ['gini','entropy'],
             'max_depth':[3,5,10,18,20,30]}

In [144]:
classifier=RandomForestClassifier()
from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(estimator=classifier, 
                    param_grid=grid_param,scoring='accuracy',cv=3)
grid.fit(train[predictors],train[target])
y_pred1 = grid.predict(test[predictors])
grid.get_params(deep=True)


{'cv': 3,
 'error_score': 'raise',
 'estimator__bootstrap': True,
 'estimator__class_weight': None,
 'estimator__criterion': 'gini',
 'estimator__max_depth': None,
 'estimator__max_features': 'auto',
 'estimator__max_leaf_nodes': None,
 'estimator__min_impurity_decrease': 0.0,
 'estimator__min_impurity_split': None,
 'estimator__min_samples_leaf': 1,
 'estimator__min_samples_split': 2,
 'estimator__min_weight_fraction_leaf': 0.0,
 'estimator__n_estimators': 10,
 'estimator__n_jobs': 1,
 'estimator__oob_score': False,
 'estimator__random_state': None,
 'estimator__verbose': 0,
 'estimator__warm_start': False,
 'estimator': RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
             oob_score=False, rand

In [153]:
df=pd.DataFrame(y_pred1)
#df.head()
df.iloc[:,0].value_counts()

0.0    5806
Name: 0, dtype: int64

In [137]:
#4.Random Forest
from sklearn.ensemble import RandomForestClassifier
predictors=[x for x in train.columns if x not in [IDcol,target,target1]]
print('Predictors:',predictors)
alg1=RandomForestClassifier(n_estimators=1000,max_depth=25,min_samples_leaf=50)
modelfit(alg1,train,test,predictors,target,IDcol,'res_RanFst.csv')

Predictors: ['principal component 1', 'principal component 2', 'principal component 3', 'principal component 4', 'principal component 5', 'principal component 6', 'principal component 7', 'principal component 8', 'principal component 9', 'principal component 10', 'principal component 11', 'principal component 12', 'principal component 13', 'principal component 14', 'principal component 15', 'principal component 16', 'principal component 17', 'principal component 18', 'principal component 19', 'principal component 20', 'ID']
F1 SCORE train 0.9389269901839097
F1 SCORE test 0.8667553692527856


In [138]:
#test.TARGET.value_counts()
res1 = pd.read_csv("res_RanFst.csv")
res1.TARGET.value_counts()

0.0    5806
Name: TARGET, dtype: int64

In [135]:
#5.AdaBoost
from sklearn.ensemble import AdaBoostClassifier
predictors = [x for x in train.columns if x not in [target]+IDcol]
# print predictors
alg1 = AdaBoostClassifier(n_estimators=200)
modelfit(alg1, train, test, predictors, target, IDcol, 'res_Adabst.csv')

[[123  69]
 [ 11 411]]


In [149]:
#6.XGBoost
from xgboost import XGBClassifier
predictors = [x for x in train.columns if x not in [target]+IDcol]
alg1 = XGBClassifier(max_depth=10, n_estimators=100, learning_rate=0.05)
modelfit(alg1, train, test, predictors, target, IDcol, 'res_xgbst.csv')

[[180  12]
 [  5 417]]


In [187]:
#7.Stacking
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from mlxtend.classifier import StackingClassifier
import numpy as np

clf1=KNeighborsClassifier(n_neighbors=1)
clf2=RandomForestClassifier(random_state=1)
clf3=DecisionTreeClassifier()
lr=LogisticRegression()
alg1=StackingClassifier(classifiers=[clf1,clf2,clf3],meta_classifier=lr)
modelfit(alg1, train, test, predictors, target, IDcol, 'res_stack.csv')

[[192   0]
 [  0 422]]
Accuracy of classifier on train set: 1.00


In [186]:
StackingClassifier?
for clf,label in zip([clf1,clf2,clf3,sclf],
                    ['KNN', 
                       'Random Forest', 
                       'Decision Tree',
                       'Stacking Regressor']):
    #Error Metrics
    confusion_matrix = confusion_matrix(train[target], sclf.)
    print(confusion_matrix)
    
    #Accuracy
    print('Accuracy of classifier on train set: {:.2f}'.format(lr.score(train[predictors],train[target])))